CREATE DATABASE DCE
USE [DCE]


CREATE TABLE Customer (
	UserId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Username VARCHAR(30),
	Email VARCHAR(20),
	FirstName VARCHAR(20),
	LastName VARCHAR(20),
	CreatedOn DATE,
	IsActive BIT DEFAULT 'false'
)

CREATE TABLE Supplier (
	SupplierId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	SupplierName VARCHAR(50),
	CreatedOn DATE,
	IsActivate BIT DEFAULT 'false'
)

CREATE TABLE Product (
	ProductId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	ProductName VARCHAR(50),
	UnitPrice DECIMAL,
	SupplierId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Supplier(SupplierId),
	CreatedOn DATE,
	IsActive BIT DEFAULT 'false'
)

CREATE TABLE Orders (
	OrderId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	ProductId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Product(ProductId),
	OrderStatus INT DEFAULT '1',
	OrderType INT DEFAULT '1',
	OrderBy UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Customer(UserId),
	OrderedOn DATE,
	ShippedOn DATE,
	IsActive BIT DEFAULT '1'
)



